# Generated by Django 3.2.7 on 2021-09-26 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyucareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ayucare',
            old_name='usedfor',
            new_name='details',
        ),
        migrations.AddField(
            model_name='ayucare',
            name='cure',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='ayucare',
            name='expiredate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ayucare',
            name='manufacturedate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
