# Generated by Django 3.2.7 on 2021-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AyucareApp', '0002_auto_20210926_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayucare',
            name='cure',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='ayucare',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
