# Generated by Django 3.2.7 on 2021-10-02 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AyucareApp', '0003_auto_20210926_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ayu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AyucareApp.ayucare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AyucareApp.user')),
            ],
        ),
    ]
